image: mleiner/kolt-base:0.2

stages:
  - build
  - integration 

build:
  stage: build
  image: python:3.6-stretch
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "apt-get update -y"
  - "apt-get install git -y"
  - "mkdir -p /builds/PI/kolt/kolt/src" 
  - "cd kolt && python3 -m venv koris-env"
  - "pip3 install pipenv"
  - "pipenv install"
  - "pip3 install -r ./requirements.txt"
  - "pip3 install -e kolt/kolt.py"

integration:
  stage: integration
  script:
    - sed -i "s/%%date%%/$(date '+%Y-%m-%d')'/g" tests/koris_test.yml
    - kolt k8s tests/koris_test.yml
    - kubectl get nodes --kubeconfig=koris-test-admin.conf
    - kubectl run nginx --image=nginx --kubeconfig=koris-test-admin.conf
    - kubectl expose deploy nginx --type=LoadBalancer
    - curl $(kubectl get --export -o jso ...)
