stages:
 - static-analysis
 - unittest
 - wait-for-resources
 - build-cluster
 - integration-test
 - resize-node
 - resize-master
 - security-checks
 - compliance-checks
 - cleanup
 - pages
 - build

# --[2]-- STATIC ANALYSIS --
static-analysis-python:
  stage: static-analysis
  image: oz123/koris-alpine:0.1.5
  script:
    - make lint

static-analysis-bash:
  stage: static-analysis
  image: oz123/koris-alpine:0.1.5
  script:
    - make test-bash


# --[2]-- UNIT TESTS --
unittest:
  stage: unittest
  image: oz123/koris-alpine:0.1.5
  script:
    - pip3 install -q -e .
    - make coverage PY=python3


# --[3]-- WAIT FOR RESOURCES --
wait-for-resources:
  stage: wait-for-resources
  image: oz123/koris-alpine:0.1.5
  script:
   - pip3 install -q -e .
   - python3 tests/scripts/wait_for_pipeline.py
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E


# --[4]-- BUILD --
bare-metal-build:
  stage: build-cluster
  image: oz123/koris-alpine:0.1.5
  script:
   - apk add openssh
   - pip install python-openstackclient python-octaviaclient
   - mkdir .ssh; echo $SSH_PRIVATE_KEY_B64 | base64 -d > .ssh/id_rsa; cat .ssh/id_rsa;
   - chmod 0600 .ssh/id_rsa; eval $(ssh-agent); ssh-add .ssh/id_rsa
   - make -f tests/makefile-bare-metal.mk build-cluster-bare-metal USER=centos CLUSTERNAME=bare-metal-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E

build-cluster:
  stage: build-cluster
  image: oz123/koris-alpine:0.1.5
  script:
  - "pip3 install -q -e ."
  - make launch-cluster
  - make show-nodes
  artifacts:
    paths:
      - "certs-*"
      - "*-admin.conf"
      - "tests/koris_test.yml"
    expire_in: 1 week
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E


# --[5]-- INTEGRATION TESTS --
bare-metal-integration:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  script:
   - apk add openssh
   - pip install python-openstackclient python-octaviaclient
   - mkdir .ssh; echo $SSH_PRIVATE_KEY_B64 | base64 -d > .ssh/id_rsa; cat .ssh/id_rsa;
   - chmod 0600 .ssh/id_rsa; eval $(ssh-agent); ssh-add .ssh/id_rsa
   - make -f tests/makefile-bare-metal.mk integration-test-bare-metal USER=centos CLUSTERNAME=bare-metal-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E

integration-test:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make integration-run"
  - "make integration-wait"
  - "make integration-patch-wait"
  - "make integration-expose"
  - "make expose-wait"
  - "make curl-run"
  - "make clean-lb-after-integration-test"
  artifacts:
    paths:
      - "certs-*"
      - "*-admin.conf"
      - "tests/koris_test.yml"
    expire_in: 1 week
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E

check-dns:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - apk add --update py3-cryptography python3-dev libffi-dev libressl-dev make
  - "pip3 install -q -e ."
  - "make check-cluster-dns"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E

check-members:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make assert-members NUM=3"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E

assert-control-plane:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make assert-masters NUM=3"
  - "make assert-control-plane NUM=3"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E

check-node-labels:
  stage: integration-test
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make assert-node ACTION=labels NUM=1"
  - "make assert-node ACTION=labels NUM=2"
  - "make assert-node ACTION=labels NUM=3"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-integration-test/
      - $SKIP_E2E


# --[6]-- RESIZE NODE --
add-nodes:
  stage: resize-node
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make add-nodes NUM=2"
  - "make assert-node ACTION=labels NUM=4"
  - "make assert-node ACTION=labels NUM=5"
  artifacts:
    paths:
      - "tests/koris_test.add_node.yml"
      - "tests/koris_test.yml"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-/
      - $SKIP_E2E

check-added-node-labels:
  stage: resize-node
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make assert-node ACTION=labels NUM=4"
  - "make assert-node ACTION=labels NUM=5"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-/
      - $SKIP_E2E

check-added-nodes-ready:
  stage: resize-node
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make assert-node ACTION=ready NUM=4"
  - "make assert-node ACTION=ready NUM=5"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-/
      - $SKIP_E2E

delete-added-nodes:
  stage: resize-node
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - "pip3 install -q -e ."
    - make delete-node NUM=5 KORIS_CONF="tests/koris_test.add_node"
    - make assert-node ACTION=deleted NUM=5
    - make delete-node NUM=4 KORIS_CONF="tests/koris_test.delete_node"
    - make assert-node ACTION=deleted NUM=4
  when: on_success
  artifacts:
    paths:
      - "tests/koris_test.delete_node.yml"
      - "tests/koris_test.yml"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-/
      - $SKIP_E2E


# --[7]-- RESIZE MASTER --
add-master:
  stage: resize-master
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - "pip3 install -q -e ."
    - "make add-master"
    - "make assert-members NUM=4"
    - "make assert-masters NUM=4"
    - "make assert-control-plane NUM=4"
  artifacts:
    paths:
      - "tests/koris_test.add_master.yml"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-master/
      - $SKIP_E2E

delete-master:
  stage: resize-master
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - "pip3 install -q -e ."
    - "make delete-node NUM=4 KORIS_CONF=tests/koris_test.add_master"
  when: on_success
  artifacts:
    paths:
      - "tests/koris_test.remove_master.yml"
      - "tests/koris_test.yml"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-resize-master/
      - $SKIP_E2E

# --[8]-- SECURITY CHECKS --
security-checks-masters:
  stage: security-checks
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install -q -e ."
  - "make security-checks-masters"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E

security-checks-nodes:
  stage: security-checks
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - apk add --update py3-cryptography python3-dev libffi-dev libressl-dev make
  - "pip3 install  -r requirements.txt"
  - "pip3 install -e ."
  - "make security-checks-nodes"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E


# --[9]-- COMPLIANCE CHECKS --
compliance-checks:
  stage: compliance-checks
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - apk add --update py3-cryptography python3-dev libffi-dev libressl-dev make
  - "pip3 install -q -e ."
  - "make compliance-checks"
  only:
  - master
  - tags
  - compliance_check
  artifacts:
    paths:
      - results
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E


# --[10]-- CLEANUP --
cleanup:
  stage: cleanup
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - apk add make
  - "pip3 install -q -e ."
  - make clean-all
  when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E

clean-bare-metal:
  stage: cleanup
  image: oz123/koris-alpine:0.1.5
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
   - pip install python-openstackclient python-octaviaclient
   - make -f tests/makefile-bare-metal.mk clean-all CLUSTERNAME=bare-metal-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
  when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_E2E


# --[11]-- PAGES --
dev-docs:
  stage: pages
  image: oz123/koris-alpine:0.1.5
  script:
  - pip3 install sphinx sphinx_rtd_theme sphinx_autobuild
  - pip3 install .
  - which sphinx-build
  - pip3 install .
  - make -C docs html
  - ls docs
  - mkdir -pv public/dev
  - ls docs/_build
  - mv docs/_build/html/ public/dev/
  artifacts:
    paths:
    - public
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "dev"

pages:
  stage: pages
  image: oz123/koris-alpine:0.1.5
  script:
  - pip3 install sphinx sphinx_rtd_theme sphinx_autobuild
  - which sphinx-build
  - pip3 install .
  - make -C docs html
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
    - tags
    - master


# --[12]-- BUILD --
build:
  stage: build
  image: oz123/koris-builder:0.2
  script:
   - make install build-exec
   - python3 setup.py sdist
  artifacts:
    paths:
     - dist/koris-*.tar.gz
     - dist/koris
  only:
    - tags
    - master
    - dev
