image: mleiner/kolt-base:0.2

test:
  script:
    - pip3 install -e .
    - make coverage PY=python3

integration:
  script:
    - kolt k8s tests/koris_test.yml
    - kubectl get nodes --kubeconfig=koris-test-admin.conf
    - kubectl run nginx --image=nginx --kubeconfig=koris-test-admin.conf
    - kubectl expose deploy nginx --type=LoadBalancer
    - curl $(kubectl get --export -o jso ...)
