image: mleiner/kolt-base:0.2

stages:
  - build

build:
  stage: build
  image: python:3.6-stretch
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "apt-get update -y"
  - "apt-get install git -y"
  - "pip3 install -e"
  - sed -i "s/%%date%%/$(date '+%Y-%m-%d')'/g" tests/koris_test.yml
  - kolt k8s tests/koris_test.yml
  - kubectl get nodes --kubeconfig=koris-test-admin.conf
  - kubectl run nginx --image=nginx --kubeconfig=koris-test-admin.conf
  - kubectl expose deploy nginx --type=LoadBalancer
