stages:
  - static-analysis
  - unittest
  - integration-test

static-analysis:
  stage: static-analysis
  image: mleiner/kolt-base:0.2
  script:
    - pip3 install flake8 pylint pylint-exit
    - make lint


unittest:
  stage: unittest
  image: mleiner/kolt-base:0.2
  script:
    - pip3 install -e .
    - make coverage PY=python3


integration-test:
  stage: integration-test
  image: mleiner/kolt-base:0.2
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
  - "pip3 install  -r requirements.txt"
  - "pip3 install -e ."
  - "mkdir  koris-install  && cd koris-install && python3 -m venv koris-env"
  - "source ./koris-env/bin/activate"
  - "cd -"
  - sed -i "s/%%date%%/$(date '+%Y-%m-%d')/g" tests/koris_test.yml
  - kolt k8s tests/koris_test.yml
  - kubectl get nodes --kubeconfig=koris-test-admin.conf
  - kubectl run nginx --image=nginx --kubeconfig=koris-test-admin.conf
  - kubectl expose deploy nginx --type=LoadBalancer

