apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: nn
  name: nn-prometheus
  namespace: nn-mon
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  type: NodePort
  selector:
    app: prometheus
    prometheus: nn
