kind: Service
apiVersion: v1
metadata:
  name:  dex-example-app
  labels:
    app: dex-example-app
spec:
  selector:
    app:  dex-example-app
  type:  LoadBalancer
  ports:
  - name: callback
    port:  5555
    targetPort:  http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dex-example-app
  name: dex-example-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dex-example-app
    spec:
      containers:
      - name: dex-example-app
        image: obitech/dex-example-app
    
      ports:
      - name: http
        containerPort: 5555

      volumeMounts:
      - name: root-ca
        mountPath: /etc/dex/tls

    volumes:
    - name: root-ca
      secret:
        secretName: dex.example.com.root-ca