# This is an example koris config file you can use to deploy a
# KUbernetes cluster into your own noris.cloud project.
---
# Noris.cloud instance flavors. For available options see
# https://www.noris.cloud/services/compute/openstack-nova/?lang=en#details
master_flavor: 'ECS.GP1.2-8'
node_flavor: 'ECS.C1.4-8'

# Specify the name of an existing network and subnet with CIDR range. If it
# doesn't exist, koris will create it for you.
private_net:
  name: 'koris-net'
  subnet:
    name: 'koris-subnet'
    cidr: '10.0.0.0/24'
    #  This is optional - if no router name is given a new one will be created
    router:
      name: 'koris-router'

# The cluster name should be unique in your OpenStack project.
cluster-name: 'koris-cluster'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a

# The number of master and worker nodes for the cluster.
# For HA, choose at least 3 each.
n-masters: 3
n-nodes: 3

# The name of the keypair in your project.
keypair: 'koris-key-pair'

# TODO: add explanation
user_data: 'cloud-init-parts/generic'

# Any generic Ubuntu image should work but if you're
# on noris.cloud, use our pre-built koris images of
# the form 'koris-YYYY-MM-DD'.
image: "koris-2019-09-12"

loadbalancer:
# This is optional - you can either remove loadbalancer and floatingip completely
# or you can Specify the Floating IP you want to assign.
  floatingip: 1.2.3.4

# The noris.cloud storage class. For available options check
# https://www.noris.cloud/services/storage/openstack-cinder/?lang=en#details
storage_class: "BSS-Performance-Storage"

# The Kubernetes pod network plugin
pod_network: "CALICO"
# The CIDR range for your internal cluster
pod_subnet: "10.233.0.0/16"

# Flannel is supported too
#pod_subnet: "10.244.0.0/16"
#pod_network: "FLANNEL"
