# Use this file if you want to deploy a cluster into the OpenStack
# PI project. For your own project or a general reference,
# use example-config.yml
---
master_flavor: 'ECS.GP1.2-8'
node_flavor: 'ECS.C1.4-8'

# Please make sure to NOT create any other networks or subnets
# into the OpenStack project by hand. It might break this setup.
# The network below is routed to office workstations so you can easily 
# SSH into them.
private_net: 'k8s-nude'
# Specifying this is only required if there are other networks present.
# subnet: 'NORIS-NUDE-OS-K8S-DEV-SUBNET'
cluster-name: 'change-me'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a
n-masters: 3
n-nodes: 3
keypair: 'your-key-pair'
#security_group: 'default'
user_data: 'cloud-init-parts/generic'
# Use the nightly koris images, if you don't have access talk 
# to the OpenStack team.
image: "koris-2019-02-08"
loadbalancer:
# set this to true if you
# want the load balancer to have a floating IP
 floatingip: false
certificates:
  expriry: 8760h
# For now a special storage class is required. If you don't
# have access, talk to the OpenStack team.
# storage_class: "BSS-Performance-Storage"
storage_class: "PI-Storage-Class"
pod_subnet: "10.233.0.0/16"
pod_network: "CALICO"
#pod_subnet: "10.244.0.0/16"
#pod_network: "FLANNEL"