# Use this file to configure the type of machines you want to create
# on OpenStack
---
master_flavor: 'ECS.GP1.2-8'
node_flavor: 'ECS.C1.4-8'
private_net: 'k8s-network'
# optionally specify the subnet
# IF YOU INTENED TO create LoadBalancer with Kubernetes you __MUST__
# specify the subnet ID.
# subnet: foo
cluster-name: 'test'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a
n-masters: 3
n-nodes: 3
n-etcds: 3
keypair: 'youruser'
user_data: 'cloud-init-parts/generic'
# while any generic *ubuntu* image will work
# you should currently use koris-base
# this image includes all k8s binaries and a special kernel
# optimized for KVM (this image is built from
# ubuntu-16.04-minimal-cloudimg-amd64-disk1.img
image: "ubuntu-16.04-koris-base"
#image: "Ubuntu Xenial Server Cloudimg"
# loadbalancer:
# set this to if you want to add this name to SAN certificates
# this is not yet implemented
# domain-name: foo.bar.noris.de
# reuse an existing floating ip from your pool
#  floatingip: 213.95.155.145

#storage_class: "BSS-Performance-Storage"
storage_class: "PI-Storage-Class"
