# Use this file to configure the type of machines you want to create
# on OpenStack
---
master_flavor: 'ECS.C1.2-4'
node_flavor: 'ECS.C1.2-4'
private_net: 'k8s-network'
# optionally specify the subnet
# subnet: foo
cluster-name: 'test2'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a
n-masters: 3
n-nodes: 3
keypair: otiram
#security_group: 'default'
user_data: 'cloud-init-parts/generic'
# while any generic *ubuntu* image will work
# you should currently use kolt-base
# this image includes all k8s binaries and a special kernel
# optimized for KVM (this image is built from
# ubuntu-16.04-minimal-cloudimg-amd64-disk1.img
image: "koris-2018-10-30"
#image: "Ubuntu Xenial Server Cloudimg"
loadbalancer:
# set this to true if you
# want the load balancer to have a floating IP
 floatingip: 213.95.155.145
#storage_class: "BSS-Performance-Storage"
storage_class: "PI-Storage-Class"
