# Use this file to configure the type of machines you want to create
# on OpenStack
---
# Noris.cloud instance flavors. For available options see
# https://www.noris.cloud/services/compute/openstack-nova/?lang=en#details
master_flavor: 'ECS.GP1.2-8'
node_flavor: 'ECS.C1.4-8'

# The project's network where your cluster should be deployed into. If you have just
# one network and subnet and in your project, koris will automatically assign the first
# subnet it finds.
private_net: 'korispipeline-office-net'
subnet: 'k8s-network'
# optionally specify the subnet
# IF YOU INTENED TO create LoadBalancer with Kubernetes you __MUST__
# specify the subnet ID.
# subnet: foo
cluster-name: 'test'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a
n-masters: 3
n-nodes: 3
keypair: 'youruser'
user_data: 'cloud-init-parts/generic'
# while any generic *ubuntu* image will work
# you should currently use koris-base
# this image includes all k8s binaries and a special kernel
# optimized for KVM (this image is built from
image: "koris-2019-YYYY-MM-DD"
# loadbalancer:
# if want the load balancer to have a floating IP, you can also specify the IP
# reuse an existing floating ip from your pool
#  floatingip: 213.95.155.145
#  floatingip: false
#  floatingip: true
#storage_class: "BSS-Performance-Storage"
storage_class: "PI-Storage-Class"
