# Use this file to configure the type of machines you want to create
# on OpenStack
---
master_flavor: 'ECS.GP1.2-8'
node_flavor: 'ECS.C1.4-8'
private_net: 'k8s-nude'
# optionally specify the subnet
# IF YOU INTENED TO create LoadBalancer with Kubernetes you __MUST__
# specify the subnet ID.
# subnet: foo
cluster-name: 'nude'
availibility-zones:
 - de-nbg6-1b
 - de-nbg6-1a
n-masters: 3
n-nodes: 3
n-etcds: 3
keypair: 'otiram'
security_group: 'k8s-nude-k8s-a0tp4t'
user_data: 'cloud-init-parts/generic'
# while any generic *ubuntu* image will work
# you should currently use kolt-base
# this image includes all k8s binaries and a special kernel
# optimized for KVM (this image is built from
# ubuntu-16.04-minimal-cloudimg-amd64-disk1.img
image: "ubuntu-16.04-kolt-base"
#image: "Ubuntu Xenial Server Cloudimg"
# set this to true if you
# want the load balancer to have a floating IP
loadbalancer-floatingip: false
certificates:
  expriry: 8760h
#storage_class: "BSS-Performance-Storage"
storage_class: "PI-Storage-Class"
